language: python
python:
    - "2.7"
install:
    - pip install pytest
    - hg clone ssh://hg@bitbucket.org/pypy/pypy
script: py.test
notifications:
    email: false
    irc: "irc.freenode.org#topaz"
