sudo: false
language: python
python: pypy-5.3.1
env:
    global:
        - secure: "VTXK/Lmi8DCoKIvg82QwlBtudV1XIRYjQbREew/ysCuvTlfp1mouZgvQQW8g\nYFNS3Ah1KTDD2qC0iZiYa7pvghlzP43M2VYr3iUxrRfiDEEIMX0jw3/n1+Sr\nWRdywivNMHhfYsEzEorW3mlwq3OmbBf4EG/UgX8c23GmW7MnwcQ="
    matrix:
        - TEST_TYPE=docs
        - TEST_TYPE=flake8
        - TEST_TYPE=own
        - TEST_TYPE=translate
        - TEST_TYPE=translate-jit
        - TEST_TYPE=rubyspec_untranslated
matrix:
    allow_failures:
        # This times out because untranslated is so slow :/
        - python: pypy-5.3.1
          env: TEST_TYPE=rubyspec_untranslated
        # We're tracking this, but not failing for it right now :(
        - python: pypy-5.3.1
          env: TEST_TYPE=flake8
    include:
      - os: osx
        language: generic
        env: TEST_TYPE=translate-jit
install:
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install wget; fi
    - pip install requests invoke
    - invoke travis.install_requirements
script: invoke travis.run_tests
after_success: invoke travis.upload_build
notifications:
    irc: "irc.freenode.org#topaz"
